import { StyleSheet, Dimensions, Platform } from "react-native";
import { vw, vh } from "react-native-css-vh-vw";
const { width, height } = Dimensions.get("window");
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

import { Font, Colors } from "style";

export default StyleSheet.create({
  container: {
    paddingHorizontal: 15,
    backgroundColor: Colors.blackBack,
  },
  wholeScreen: {
    paddingVertical: 30,
    height: "100%",
    backgroundColor: Colors.blackBack,
  },
  header: {
    marginTop: height > 812 && Platform.OS == "ios" ? hp("5%") : 60,
    height: 65,
    paddingHorizontal: 10,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomColor: "#5F66744D",
    borderBottomWidth: 1,
  },
  logoContainer: {
    justifyContent: "center", //Centered vertically
    flex: 1,
  },
  hamburgerBtn: {
    marginTop: 10,
  },
  title: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 28,
    marginHorizontal: 10,
  },
  titleLabel: {
    fontFamily: Font.FontFamily.EurostileBold,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: 0.15,
    color: Colors.white,
  },
  itemCount: {
    fontFamily: Font.FontFamily.SpaceGrotesk,
    fontSize: 14,
    lineHeight: 22,
    letterSpacing: 0.8,
    color: Colors.grey,
  },
  qrContainer: {
    backgroundColor: "#161820",
    borderRadius: 12,
    marginHorizontal: 4,
  },
  linearBorder: {
    position: "absolute",
    width: vw(100) - 36,
    marginHorizontal: 3,
    height: 400,
    borderRadius: 12,
    top: 50,
  },
  qr: {
    width: vw(100) - 50,
    height: height > 812 && Platform.OS == "ios" ? 325 : hp("30%"),
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  qrImg: {
    borderBottomColor: "#5F66744D",
    borderBottomWidth: 2,
    marginBottom: 20,
  },
  itemLabel: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    backgroundColor: Colors.red,
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  itemLabelString: {
    color: Colors.white,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.15,
    fontWeight: "800",
  },
  infoContainer: {
    alignContent: "center",
    alignItems: "center",
  },
  itemTitle: {
    fontSize: hp("4%"),
    fontFamily: Font.FontFamily.EurostileBold,
    lineHeight: hp("4%"),
    fontWeight: "700",
    letterSpacing: 1,
    color: Colors.white,
    marginTop: 35,
  },
  infoString: {
    fontSize: 12,
    paddingHorizontal: 36,
    textAlign: "center",
    marginTop: 13,
    lineHeight: 16,
    letterSpacing: 0.8,
    color: Colors.white,
    fontWeight: "400",
  },
  itemSubtitle: {
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
    letterSpacing: 3,
    marginTop: 28,
    marginBottom: 18,
  },
  circleImg: {
    // width: 86,
    // height: 83,
    // borderWidth: 2,
    borderRadius: 73,
    // borderColor: Colors.white,
    position: "absolute",
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    top: -58,
  },
  linearCircle: {
    // width: 82,
    // height: 79,
    width: 86,
    height: 83,
    top: -61.5,
    position: "absolute",
    borderWidth: 2,
    borderRadius: Platform.OS == "ios" ? 43 : 73,
    borderColor: Colors.white,
  },
  button: {
    height: 50,
    width: 157,
  },
  buttonText: {
    fontSize: 14,
    lineHeight: 24,
    fontFamily: Font.FontFamily.EurostileBold,
    letterSpacing: 0.15,
    color: Colors.white,
  },
  linearbutton: {
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderWidth: 2,
    borderRadius: Platform.OS == "ios" ? 25 : 20,
    borderColor: "#E9267B4D",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  buttonLeftPart: {
    display: "flex",
    flexDirection: "row",
  },
  buttonRightPart: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  bottomActionContainer: {
    paddingTop: 30,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  navBtn: {
    paddingVertical: 13,
    width: 70,
    borderWidth: 1,
    borderColor: "#242732",
    borderRadius: 37,
    backgroundColor: "#161820",
    alignItems: "center",
  },
  bottomLabel: {
    fontSize: 14,
    color: Colors.grey,
    letterSpacing: 0.15,
  },
});
